# actions/run_plan.py

from .base import Action
from ..utils import display_in_panel
from .base import ActionFailureException
from .create_plan import CreatePlanAction
import json


class RunPlanAction(Action):
    description = "Run the plan generated by CreatePlanAction."
    default_openinference_span_kind: str = "chain"  # sets the default span kind for tracing the run method

    def _execute_single_plan(self, plan, mode: str) -> bool:
        """
        Execute a single plan once.

        Returns:
            True if the plan completed successfully.
            False if it failed due to an ActionFailureException.
        """
        if self.agent is None:
            display_in_panel(
                "No agent attached to RunPlanAction.",
                title="Error",
            )
            return False

        history_len_before_plan = len(self.agent.history) - 1
        total_steps = len(plan.plan_steps)

        # Prepare all action instances, linked for parent/child dispatch
        actions_to_run = []
        prev_action_instance = None

        for step_index, step in enumerate(plan.plan_steps, start=1):
            action_name = step.action_name.value
            # Find the action class in available_actions
            action_class = None
            for action in self.agent.available_actions:
                if action.__class__.__name__ == action_name:
                    action_class = action.__class__
                    break
            if not action_class:
                print(f"[Error] Could not find action class: {action_name}")
                continue

            # Instantiate the action, pass tracer if possible
            try:
                action_instance = action_class(
                    tracer=self.tracer, agent=self.agent
                )
            except TypeError:
                # fallback in case action class does not support tracer in init
                action_instance = action_class()

            # Chain parent/child references
            if prev_action_instance is not None:
                action_instance.parent = prev_action_instance
                prev_action_instance.child = action_instance
            actions_to_run.append((action_instance, step_index, step))

            prev_action_instance = action_instance

        # Execute all actions in sequence, formatting input and displaying progress
        for action_instance, step_index, step in actions_to_run:
            action_name = step.action_name.value
            plan_repr = (
                f"Full Plan:\n"
                f"- User Request: {plan.user_request}\n"
                f"- Overall Goal: {plan.overall_plan_goal}\n"
                f"- Plan Description: {plan.plan_description}\n"
                f"- Number of Steps: {total_steps}\n"
            )
            step_repr = (
                f"\nCurrent Plan Step [{step_index}/{total_steps}]:\n"
                f"- Step Name: {step.step_name}\n"
                f"- Step Description: {step.step_description}\n"
                f"- Action Name: {action_name}\n"
            )

            user_input_for_action = (
                f"{plan_repr}{step_repr}\n"
                f"{step.custom_user_input}\n\n"
                "### Relevant History Since Plan Started ###\n"
                + "\n".join(
                    [
                        f"{msg['role']}: {msg['content']}"
                        for msg in self.agent.history[history_len_before_plan:]
                    ]
                )
            )

            display_in_panel(
                f"**Plan Progress: {step_index}/{total_steps}**\n\n"
                f"**Current Action:** {action_name}\n\n"
                f"**Step Instructions:**\n{step.custom_user_input}",
                title="Plan Execution Progress",
                padding_left=5,
                padding_right=5,
            )

            try:
                action_instance.run(user_input_for_action, mode)
            except ActionFailureException:
                # The failure is already logged and added to history by the action.
                display_in_panel(
                    "Execution aborted due to action failure",
                    title="Plan Execution Aborted",
                )
                return False

        # assume plan finished without errors, returning anything
        # to indicate success
        display_in_panel(
            "✅ Plan execution completed.", title="Plan Execution Completed"
        )
        return True

    def _build_replan_context(self, plan) -> str:
        """
        Build a string that contains the information needed for replanning:
        - Original user request
        - The previous plan
        - The agent's output history up to and including the last failure
        """
        if self.agent is None:
            return ""

        original_request = getattr(
            self.agent, "original_user_request", plan.user_request
        )

        # Serialize the prior plan in a model-friendly way
        try:
            plan_dict = plan.model_dump()
        except AttributeError:
            # Fallback if plan is not a Pydantic model for some reason
            plan_dict = str(plan)

        history_snippets = []
        for msg in self.agent.history:
            role = msg.get("role", "")
            content = msg.get("content", "")
            history_snippets.append(f"{role}: {content}")

        history_text = "\n".join(history_snippets)

        context = (
            "The previous attempt to execute a plan has failed. "
            "You must generate a new and improved plan that avoids the previous failure.\n\n"
            "=== Original User Request ===\n"
            f"{original_request}\n\n"
            "=== Previous Plan (JSON) ===\n"
            f"{json.dumps(plan_dict, indent=2, default=str)}\n\n"
            "=== Conversation and Action History (including the failure message) ===\n"
            f"{history_text}\n\n"
            "Use this information to create a revised plan that is more likely to succeed. "
            "Focus especially on addressing the cause of the last failure."
        )
        return context

    def _run_impl(self, user_input: str, mode: str):
        """
        Run the current plan with retry logic.

        When an action fails, this will:
        - Build a replan context containing the original user request,
          the previous plan, and the full history including the failure.
        - Invoke CreatePlanAction again to create a new plan.
        - Retry execution with the new plan, up to max_plan_retries times.
        """
        if self.agent is None:
            display_in_panel("No agent attached.", title="Error")
            return

        if (
            not hasattr(self.agent, "current_plan")
            or not self.agent.current_plan
        ):
            display_in_panel(
                "No plan found. Please create a plan first.", title="Error"
            )
            return

        # Track the original user request on the agent so CreatePlanAction
        # can always use it when generating plans or replans.
        if not getattr(self.agent, "original_user_request", None):
            self.agent.original_user_request = (
                self.agent.current_plan.user_request
                if hasattr(self.agent.current_plan, "user_request")
                else user_input
            )

        max_retries = getattr(self.agent, "max_plan_retries", 1)
        attempt = 0

        while attempt <= max_retries:
            current_plan = self.agent.current_plan
            display_in_panel(
                f"Starting plan execution attempt {attempt + 1} of {max_retries + 1}.",
                title="Plan Execution Attempt",
            )

            success = self._execute_single_plan(current_plan, mode)
            if success:
                return "Plan execution finished successfully."

            # If this attempt failed and we have retries left, replan
            attempt += 1
            if attempt > max_retries:
                display_in_panel(
                    "Maximum plan retries reached. Aborting.",
                    title="Plan Retry Limit Reached",
                )
                return

            # Build context for replanning
            replan_context = self._build_replan_context(current_plan)
            # Store the replan context on the agent so CreatePlanAction can read it
            self.agent.replan_context = replan_context

            display_in_panel(
                "Replanning after failure. Generating a new improved plan.",
                title="Replan",
            )

            # Invoke CreatePlanAction directly to generate a new plan
            create_plan_action = CreatePlanAction(
                agent=self.agent, tracer=self.tracer
            )
            # For replanning, pass some label as user_input; the actual
            # original request is carried via agent.original_user_request,
            # and replan_context is on agent.replan_context.
            try:
                create_plan_action.run(
                    user_input=self.agent.original_user_request, mode=mode
                )
            except ActionFailureException:
                display_in_panel(
                    "Replanning failed. Aborting.",
                    title="Replan Failure",
                )
                return

        # If control somehow reaches here, consider it a failure
        display_in_panel(
            "Plan execution failed after retries.", title="Plan Failure"
        )
        return
